### ISSUE TITLE
Handling Error in Listener Callback

### ISSUE THREAD

**Issue by vigneshnrfs** [seneca-contrib/seneca-amqp-transport#23]
Hi.

I am sure that there is a lot of discussion happening around error handling at https://github.com/senecajs/seneca/issues/398

But I wanted to know if the below scenario is inherent to amqp-transport.

So a microservice 

```
seneca.add('otp:verify', function (args, cb) {

  redis.pttl(`otp:${args.id}`).then(function (time) {
    console.log(typeof time, time);
    if (time <= 0) {
      return cb({success:false,errorCode:1002,message:'OTP EXPIRED'});
    }

  });

});
```

Calling the above throws  an error and kills the process.
```
Seneca Fatal Error
==================

Message: seneca: Action otp:verify failed: gate-executor: action-error.

Code: act_execute

Details: { id: 'np6rnxa4j9zy/gbn0aq2wlxid',
  gate: false,
  ungate: true,
  desc: 'otp:verify',
  cb: [Function],
  plugin: { name: 'root$', tag: undefined },
  fn: [Function],
  time: { start: 1461393871342, end: 1461393871344 },
  message: 'gate-executor: action-error',
  pattern: 'otp:verify',
  instance: 'Seneca/0.7.2/xslhf5tt28gk/1461393809134/3107/-',
  'orig$': 
   { [Error: gate-executor: action-error]
     eraro: true,
     orig: null,
     code: 'unknown',
     'gate-executor': true,
     package: 'gate-executor',
     msg: 'gate-executor: action-error',
     details: 
      { id: 'np6rnxa4j9zy/gbn0aq2wlxid',
        gate: false,
        ungate: true,
        desc: 'otp:verify',
        cb: [Function],
        plugin: { name: 'root$', tag: undefined },
        fn: [Function],
        time: { start: 1461393871342, end: 1461393871344 } },
     callpoint: 'at /home/zapstitch/IdeaProjects/plento_ecospace/otp/node_modules/seneca/node_modules/gate-executor/gate-executor.js:122:23' },
  'message$': 'gate-executor: action-error' }

```

On the client side, I get the seneca timeout error.

Now I do the below changes 
```
  seneca.add('otp:verify', function (args, cb) {

  redis.pttl(`otp:${args.id}`).then(function (time) {
    console.log(typeof time, time);
    if (time <= 0) {

      var error = new Error('OTP EXPIRED');
      return cb(error);
    }

   
  });

});
```

Also it throws an error and kills the process.
```
Seneca Fatal Error
==================

Message: seneca: Action otp:verify failed: OTP EXPIRED.

Code: act_execute

Details: { id: 'np6rnxa4j9zy/gbn0aq2wlxid',
  gate: false,
  ungate: true,
  desc: 'otp:verify',
  cb: [Function],
  plugin: { name: 'root$', tag: undefined },
  fn: [Function],
  time: { start: 1461394294407, end: 1461394294408 },
  'orig$': [Error: OTP EXPIRED],
  'message$': 'OTP EXPIRED',
  message: 'OTP EXPIRED',
  pattern: 'otp:verify',
  instance: 'Seneca/0.7.2/6pgvd4zmdfta/1461394293874/3510/-' }

Stack: 
    at /home/zapstitch/IdeaProjects/ecospace/otp/modules/generate_otp/services/generate_otp.js:24:19
    at tryCatcher (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Instance: Seneca/0.7.2/6pgvd4zmdfta/1461394293874/3510/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/home/zapstitch/IdeaProjects/ecospace/otp/node_modules/seneca/seneca.js:1529:29)

When: 2016-04-23T06:51:34.417Z

Log: [sys,seneca,0.7.2,6pgvd4zmdfta/1461394293874/3510/-,act_execute,seneca: Action otp:verify failed: OTP EXPIRED.,

```

What is the right approach here?

**Comment by nfantone** [comment]
@vigneshnrfs Well... it all depends on what you are after, really. If you pass _any_ truthy value as the first argument of the `cb` callback, Seneca will interpret that your action has failed and won't respond to the client. And, unless you call it with `fatal$:false`, it will also consider it to be a _fatal_ error and just blow up. This is a tad extreme, in my opinion - and is one of the reasons the core team is revising error handling.

So, to answer your question:

1) Don't pass an error (or any truthy value) to the first argument of the callback, unless some unexpected or unrecoverable event occurs.
2) Instead, if you want to notify the client about an error, use something like this:

```js
  seneca.add('otp:verify', function (args, cb) {

  redis.pttl(`otp:${args.id}`).then(function (time) {
    console.log(typeof time, time);
    if (time <= 0) {
      return cb(null, { success: false, error: 'OTP EXPIRED'});
    }
    return cb(null, { success: true });
  }).catch(cb);
});
```

If you are using [bluebird](http://bluebirdjs.com/), syntax becomes a little more readable:

```js
  seneca.add('otp:verify', function (args, cb) {

  redis.pttl(`otp:${args.id}`).then(function (time) {
    console.log(typeof time, time);
    if (time <= 0) {
      return { success: false, error: 'OTP EXPIRED'};
    }
    return { success: true };
  }).asCallback(cb);
});
```
3) _Always call the callback_. If you fail to do that, the client will just hang (or timeout, eventually).

On a side note, if you are able, try upgrading your Seneca version to latest. `0.7.2` is rather old now.

**Comment by vigneshnrfs** [comment]
Thanks @nfantone . In fact, I started using the above approach in my development.

```return cb(null, { success: false, error: 'OTP EXPIRED'});```

But it just doesn't feel good using errors this way as it adds additional validations on the client callback and is not in tune with node js convention.

But I guess, we will have to wait and see what the seneca comes up with in the future.

And thanks for pointing me at the version. I have updated it now :)

**Comment by nfantone** [comment]
> But it just doesn't feel good using errors this way as it adds additional validations on the client callback

You'd always have that. You _should_, at least. How else would you know if a listener failed? 

> and is not in tune with node js convention.

What convention would that be? If you're writing about [error-first callbacks](http://thenodeway.io/posts/understanding-error-first-callbacks/) Seneca is very much aligned with that. It just does't _interpret_ the meaning of errors the way you want/need in this scenario. In fact, not even that `redis` library you're using considers your validation an "error", since the promise resolves just fine. Validations and business rules (such as your `time <= 0` check) should _not_ be treated as errors because it is assumed that you want clients to know and act upon them.

> And thanks for pointing me at the version. I have updated it now :)

You're welcome! Feel free to close the issue if you have no further questions, @vigneshnrfs

**Comment by nfantone** [comment]
Closing due to inactivity.

**Comment by ibobo** [comment]
I found a solution, you must set:
`seneca.fixedargs['fatal$'] = false;`
at the start of your service, the one that actually returns the error.
