### ISSUE TITLE
Exception when integrate to Express

### ISSUE THREAD

**Issue by jackyphuong** [seneca-contrib/seneca-amqp-transport#36]
Hello,

Currently, I am trying to integrate Seneca with Express. 

It will work well if we act like below code
let seneca = require('seneca')()
    .use('seneca-amqp-transport');
let client = seneca.client({
        type: 'amqp',
        url: '....',
        pin: 'role:communicationservice'
    });

client.act({ role: 'communicationservice', cmd: 'ping' }, (err, result) => {
    if (err) {
        console.log(err);
    }
   console.log(result);
});

However, when we include into express routing, it throw exception
let seneca = require('seneca')()
    .use('seneca-amqp-transport');
let client = seneca.client({
        type: 'amqp',
        url: '.......'
        pin: 'role:communicationservice'
    });
let express = require('express');
let router = express.Router();

router.get('/ping', (req, res, next) => {
    console.log('123456');    
    client.act({ role: 'communicationservice', cmd: 'ping' }, (err, result) => {
        if (err) {
            console.log(err);
            res.statusCode(500).json(err);
        }
        console.log(result);
        res.json(result);
    });
})

module.exports = router;

2016-06-23T06:46:42.937Z q8vwu2cu607j/1466664390127/8160/- ERROR	act	amqp-transport	OUT		hook:client,role:transport,type:amqp	10518	{type:amqp,url:amqp://xxxx,pin:role:communicationservice,pg:role:communicatio	ENTRY	(izp9dgqiwqoe)	-	seneca: Action hook:client,role:transport,type:amqp failed: read ECONNRESET.	act_execute	{id:fwz0l2kbsucg/j11mkslegzpj,gate:false,ungate:true,desc:null,time:{start:1466664392401,end:1466664402914},mes	Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)	
2016-06-23T06:46:42.937Z q8vwu2cu607j/1466664390127/8160/- FATAL	plugin	client$       	sys	seneca	2.1.0	q8vwu2cu607j/1466664390127/8160/-	act_execute	seneca: Action hook:client,role:transport,type:amqp failed: read ECONNRESET.	{id:fwz0l2kbsucg/j11mkslegzpj,gate:false,ungate:true,desc:null,time:{start:1466664392401,end:1466664402914},mes	all-errors-fatal	
2016-06-23T06:46:43.519Z q8vwu2cu607j/1466664390127/8160/- ERROR	act	transport	OUT		cmd:client,role:transport	13168	{config:{type:amqp,url:amqp://.....,pin:role:communicationservice,pg:role:comm	ENTRY	(7bx5qybvvz5f)	GATE	seneca: Action cmd:client,role:transport failed: [TIMEOUT:9pevg91qhh3e/j11mkslegzpj:11111<1466664403510-1466664392398:undefined].	act_execute	{id:9pevg91qhh3e/j11mkslegzpj,gate:true,ungate:true,desc:null,time:{start:1466664392398,end:1466664403510},mess	Error: [TIMEOUT:9pevg91qhh3e/j11mkslegzpj:11111<1466664403510-1466664392398:undefined]
    at null._onTimeout (d:\Research\Git\NodeJS\demo-micro-service\src\node_modules\seneca\node_modules\gate-executor\gate-executor.js:112:21)
    at Timer.listOnTimeout (timers.js:92:15)	
2016-06-23T06:46:43.520Z q8vwu2cu607j/1466664390127/8160/- FATAL	plugin	client$       	sys	seneca	2.1.0	q8vwu2cu607j/1466664390127/8160/-	act_execute	seneca: Action cmd:client,role:transport failed: [TIMEOUT:9pevg91qhh3e/j11mkslegzpj:11111<1466664403510-1466664392398:undefined].

           'tx$': 'j11mkslegzpj' },
        delegate: [Function],
        context: {},
        client: [Function],
        listen: [Function],
        makelogfuncs: [Function],
        log: 
         { [Function]
           debug: [Function],
           info: [Function],
           warn: [Function],
           error: [Function],
           fatal: [Function] },
        prior: [Function],
        good: [Function],
        bad: [Function] } },
  fn: [Function],
  time: { start: 1466664392401, end: 1466664402914 },
  'orig$': { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  'message$': 'read ECONNRESET',
  message: 'read ECONNRESET',
  pattern: 'hook:client,role:transport,type:amqp',
  instance: 'Seneca/2.1.0/q8vwu2cu607j/1466664390127/8160/-',
  plugin: {} }
Stack: 
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)

Could you let me know what is wrong?

Thanks,

Phuong Le

**Comment by nfantone** [comment]
@jackyphuong Well, looks like Seneca can't reach the AMQP broker. Did you check the AMQP URI you are setting on the client? Isn't the Express server running on the same port, per chance?

**Comment by nfantone** [comment]
@jackyphuong Any updates on this? I'm considering closing the issue due to inactivity.
