### ISSUE TITLE
RabbitMQ: Unknown delivery tag 1

### ISSUE THREAD

**Issue by OriginalEXE** [seneca-contrib/seneca-amqp-transport#50]
Hello,

I just came across this error, the reason why I'm opening an issue is because it seems to have some sort of relation to the AMQP transport plugin, even though I'm not sure why it happened only now, since I've been using it for quite some time in the same way, and never had this happen.

Here is the error log from the console:

```
api-server_1             | 23:29:34 api-server-0 (node:16) Warning: a promise was created in a handler at /home/service/api-server/node_modules/amqplib/lib/channel.js:316:9 but was not returned from it, see http://goo.gl/rRqMUw
api-server_1             | 23:29:34 api-server-0     at ret (eval at <anonymous> (/home/service/api-server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
rabbitmq-api_1           | 
rabbitmq-api_1           | =ERROR REPORT==== 21-Sep-2016::23:29:34 ===
rabbitmq-api_1           | Channel error on connection <0.757.0> (172.18.0.13:33284 -> 172.18.0.4:5672, vhost: '/', user: 'guest'), channel 1:
rabbitmq-api_1           | operation basic.ack caused a channel exception precondition_failed: "unknown delivery tag 1"
api-server_1             | 23:29:34 api-server-0 ["client","unknown_message_id",{"pin":"role:api,path:tokens","type":"amqp","url":"amqp://rabbitmq-api","pg":"path:tokens,role:api","id":"pg:path:tokens,role:api,pin:role:api,path:tokens,type:amqp,url:amqp://rabbitmq-api","role":"transport","hook":"client","exchange":{"type":"topic","name":"seneca.topic","options":{"durable":true,"autoDelete":false}},"queues":{"action":{"prefix":"seneca","separator":".","options":{"durable":true}},"response":{"prefix":"seneca.res","separator":".","options":{"autoDelete":true,"exclusive":true}}}},{"id":"6hbvam631og7/q04ynyzdhmyg","kind":"res","origin":"i12msb2n0ocm/1474500567450/16/3.0.0/-","accept":"5nbd5oa1lyjg/1474500567307/16/3.1.0/-","track":["i12msb2n0ocm/1474500567450/16/3.0.0/-"],"time":{"client_sent":1474500574358,"listen_recv":1474500574363,"listen_sent":1474500574405,"client_recv":1474500574439},"sync":true,"res":{"data":{"id":"19fb83a0-891c-4248-ba0a-d8fc04de1a43","type":"password:update","userId":"e3bce0ea-b203-4776-a204-5003021e55ea"}}}]
api-tokens_1             | 23:29:34 0|api-toke | {"notice":"seneca: Action hook:listen,role:transport,type:amqp failed: Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\".","code":"act_execute","err":{"code":"act_execute","eraro":true,"orig":{"code":406},"seneca":true,"package":"seneca","msg":"seneca: Action hook:listen,role:transport,type:amqp failed: Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\".","details":{"message":"Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\"","pattern":"hook:listen,role:transport,type:amqp","instance":"Seneca/5nbd5oa1lyjg/1474500567307/16/3.1.0/-","orig$":{"code":406},"message$":"Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\"","plugin":{}},"callpoint":"at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:406:17)"},"actid":"kyk7t76f8hkz/a4te2ck5gegj","msg":{"pin":"role:api,path:tokens","type":"amqp","url":"amqp://rabbitmq-api","msgprefix":"seneca_","callmax":111111,"msgidlen":12,"role":"transport","hook":"listen","plugin$":{"name":"transport","tag":"-"},"tx$":"a4te2ck5gegj","meta$":{"id":"m7m1nlbrunu5/a4te2ck5gegj","tx":"a4te2ck5gegj","start":1474500567742,"pattern":"hook:listen,role:transport,type:amqp","action":"(eftl2hmek99h)","entry":true,"chain":[],"sync":true,"plugin_name":"amqp-transport","plugin_tag":"-"}},"entry":true,"prior":[],"meta":{"plugin_name":"amqp-transport","plugin_tag":"-","plugin_fullname":"amqp-transport","raw":{"role":"transport","hook":"listen","type":"amqp"},"sub":false,"client":false,"args":{"role":"transport","hook":"listen","type":"amqp"},"rules":{},"id":"(eftl2hmek99h)","pattern":"hook:listen,role:transport,type:amqp","msgcanon":{"hook":"listen","role":"transport","type":"amqp"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":6698,"level":"error","plugin_name":"transport","plugin_tag":"-","pattern":"cmd:listen,role:transport","seneca":"5nbd5oa1lyjg/1474500567307/16/3.1.0/-","when":1474500574459}
api-tokens_1             | 23:29:34 0|api-toke | {"notice":"seneca: Action hook:listen,role:transport,type:amqp failed: Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\".","code":"act_execute","err":{"code":"act_execute","eraro":true,"orig":{"code":406},"seneca":true,"package":"seneca","msg":"seneca: Action hook:listen,role:transport,type:amqp failed: Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\".","details":{"message":"Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\"","pattern":"hook:listen,role:transport,type:amqp","instance":"Seneca/5nbd5oa1lyjg/1474500567307/16/3.1.0/-","orig$":{"code":406},"message$":"Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\"","plugin":{}},"callpoint":"at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:406:17)"},"actid":"kyk7t76f8hkz/a4te2ck5gegj","msg":{"config":{"pin":"role:api,path:tokens","type":"amqp","url":"amqp://rabbitmq-api","msgprefix":"seneca_","callmax":111111,"msgidlen":12},"gate$":true,"role":"transport","cmd":"listen","meta$":{"id":"kyk7t76f8hkz/a4te2ck5gegj","tx":"a4te2ck5gegj","start":1474500567741,"pattern":"cmd:listen,role:transport","action":"(a2ye4muxbpk8)","entry":true,"chain":[],"sync":true,"plugin_name":"transport","plugin_tag":"-"},"plugin$":{"name":"transport","tag":"-"},"tx$":"a4te2ck5gegj"},"entry":true,"prior":[],"gate":true,"meta":{"plugin_name":"transport","plugin_tag":"-","plugin_fullname":"transport","raw":{"role":"transport","cmd":"listen"},"sub":false,"client":false,"args":{"role":"transport","cmd":"listen"},"rules":{},"id":"(a2ye4muxbpk8)","pattern":"cmd:listen,role:transport","msgcanon":{"cmd":"listen","role":"transport"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":6719,"level":"error","seneca":"5nbd5oa1lyjg/1474500567307/16/3.1.0/-","when":1474500574460}
api-tokens_1             | 23:29:34 0|api-toke | []
api-tokens_1             | 23:29:34 0|api-toke | ["Channel failed to close",{"message":"Channel closed","stack":"IllegalOperationError: Channel closed\n    at Channel.<anonymous> (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:149:11)\n    at Channel.C.closeBecause (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:201:8)\n    at Channel.C.close (/home/service/api-tokens/node_modules/amqplib/lib/channel_model.js:81:8)\n    at Seneca.<anonymous> (/home/service/api-tokens/node_modules/seneca-amqp-transport/lib/hook.js:18:29)\n    at Array.done (/home/service/api-tokens/node_modules/seneca/seneca.js:950:22)\n    at validate_action_message (/home/service/api-tokens/node_modules/seneca/seneca.js:1398:19)\n    at execute_action (/home/service/api-tokens/node_modules/seneca/seneca.js:880:7)\n    at Object.execspec.fn [as orig_fn] (/home/service/api-tokens/node_modules/seneca/seneca.js:1084:11)\n    at Object.timeout_fn [as fn] (/home/service/api-tokens/node_modules/gate-executor/gate-executor.js:194:12)\n    at next (/home/service/api-tokens/node_modules/gate-executor/gate-executor.js:126:14)\n    at process (/home/service/api-tokens/node_modules/gate-executor/gate-executor.js:175:12)\n    at Immediate.<anonymous> (/home/service/api-tokens/node_modules/gate-executor/gate-executor.js:165:13)\n    at runCallback (timers.js:574:20)\n    at tryOnImmediate (timers.js:554:5)\n    at processImmediate [as _immediateCallback] (timers.js:533:5)","stackAtStateChange":"Stack capture: Channel closed by server: 406 (PRECONDITION-FAILED) with message \"PRECONDITION_FAILED - unknown delivery tag 1\"\n    at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:410:13)\n    at Connection.mainAccept [as accept] (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:63:33)\n    at Socket.go (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:476:48)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at emitReadable_ (_stream_readable.js:433:10)\n    at emitReadable (_stream_readable.js:427:7)\n    at readableAddChunk (_stream_readable.js:188:13)\n    at Socket.Readable.push (_stream_readable.js:135:10)\n    at TCP.onread (net.js:542:20)"}]
api-tokens_1             | 23:29:34 0|api-toke | Seneca Fatal Error
api-tokens_1             | 23:29:34 0|api-toke | ==================
api-tokens_1             | 23:29:34 0|api-toke | Message: seneca: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1"
api-tokens_1             | 23:29:34 0|api-toke | Code: transport_listen
api-tokens_1             | 23:29:34 0|api-toke | Details: { pin: 'role:api,path:tokens',
api-tokens_1             | 23:29:34 0|api-toke |   type: 'amqp',
api-tokens_1             | 23:29:34 0|api-toke |   url: 'amqp://rabbitmq-api',
api-tokens_1             | 23:29:34 0|api-toke |   msgprefix: 'seneca_',
api-tokens_1             | 23:29:34 0|api-toke |   callmax: 111111,
api-tokens_1             | 23:29:34 0|api-toke |   msgidlen: 12,
api-tokens_1             | 23:29:34 0|api-toke |   'orig$': 
api-tokens_1             | 23:29:34 0|api-toke |    { Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1"
api-tokens_1             | 23:29:34 0|api-toke |        at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:406:17)
api-tokens_1             | 23:29:34 0|api-toke |        at Connection.mainAccept [as accept] (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:63:33)
api-tokens_1             | 23:29:34 0|api-toke |        at Socket.go (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:476:48)
api-tokens_1             | 23:29:34 0|api-toke |        at emitNone (events.js:86:13)
api-tokens_1             | 23:29:34 0|api-toke |        at Socket.emit (events.js:185:7)
api-tokens_1             | 23:29:34 0|api-toke |        at emitReadable_ (_stream_readable.js:433:10)
api-tokens_1             | 23:29:34 0|api-toke |        at emitReadable (_stream_readable.js:427:7)
api-tokens_1             | 23:29:34 0|api-toke |        at readableAddChunk (_stream_readable.js:188:13)
api-tokens_1             | 23:29:34 0|api-toke |        at Socket.Readable.push (_stream_readable.js:135:10)
api-tokens_1             | 23:29:34 0|api-toke |        at TCP.onread (net.js:542:20)
api-tokens_1             | 23:29:34 0|api-toke |      code: 'act_execute',
api-tokens_1             | 23:29:34 0|api-toke |      eraro: true,
api-tokens_1             | 23:29:34 0|api-toke |      orig: 
api-tokens_1             | 23:29:34 0|api-toke |       { Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1"
api-tokens_1             | 23:29:34 0|api-toke |           at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:406:17)
api-tokens_1             | 23:29:34 0|api-toke |           at Connection.mainAccept [as accept] (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:63:33)
rabbitmq-api_1           | 
rabbitmq-api_1           | =WARNING REPORT==== 21-Sep-2016::23:29:34 ===
rabbitmq-api_1           | closing AMQP connection <0.757.0> (172.18.0.13:33284 -> 172.18.0.4:5672):
rabbitmq-api_1           | client unexpectedly closed TCP connection
api-tokens_1             | 23:29:34 0|api-toke |           at Socket.go (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:476:48)
api-tokens_1             | 23:29:34 0|api-toke |           at emitNone (events.js:86:13)
api-tokens_1             | 23:29:34 0|api-toke |           at Socket.emit (events.js:185:7)
api-tokens_1             | 23:29:34 0|api-toke |           at emitReadable_ (_stream_readable.js:433:10)
api-tokens_1             | 23:29:34 0|api-toke |           at emitReadable (_stream_readable.js:427:7)
api-tokens_1             | 23:29:34 0|api-toke |           at readableAddChunk (_stream_readable.js:188:13)
api-tokens_1             | 23:29:34 0|api-toke |           at Socket.Readable.push (_stream_readable.js:135:10)
api-tokens_1             | 23:29:34 0|api-toke |           at TCP.onread (net.js:542:20) code: 406 },
api-tokens_1             | 23:29:34 0|api-toke |      seneca: true,
api-tokens_1             | 23:29:34 0|api-toke |      package: 'seneca',
api-tokens_1             | 23:29:34 0|api-toke |      msg: 'seneca: Action hook:listen,role:transport,type:amqp failed: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1".',
api-tokens_1             | 23:29:34 0|api-toke |      details: 
api-tokens_1             | 23:29:34 0|api-toke |       { message: 'Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1"',
api-tokens_1             | 23:29:34 0|api-toke |         pattern: 'hook:listen,role:transport,type:amqp',
api-tokens_1             | 23:29:34 0|api-toke |         fn: [Function],
api-tokens_1             | 23:29:34 0|api-toke |         cb: 
api-tokens_1             | 23:29:34 0|api-toke |          { [Function: bound ]
api-tokens_1             | 23:29:34 0|api-toke |            seneca: 
api-tokens_1             | 23:29:34 0|api-toke |             Seneca {
api-tokens_1             | 23:29:34 0|api-toke |               'private$': {},
api-tokens_1             | 23:29:34 0|api-toke |               did: '(p7ip5527o5xr)',
api-tokens_1             | 23:29:34 0|api-toke |               toString: [Function],
api-tokens_1             | 23:29:34 0|api-toke |               fixedargs: 
api-tokens_1             | 23:29:34 0|api-toke |                { 'plugin$': { name: 'transport', tag: '-' },
api-tokens_1             | 23:29:34 0|api-toke |                  'tx$': 'a4te2ck5gegj' },
api-tokens_1             | 23:29:34 0|api-toke |               delegate: [Function],
api-tokens_1             | 23:29:34 0|api-toke |               context: {},
api-tokens_1             | 23:29:34 0|api-toke |               client: [Function],
api-tokens_1             | 23:29:34 0|api-toke |               listen: [Function],
api-tokens_1             | 23:29:34 0|api-toke |               log: 
api-tokens_1             | 23:29:34 0|api-toke |                { [Function: prepare_log_data]
api-tokens_1             | 23:29:34 0|api-toke |                  debug: [Function: prepare_log_data],
api-tokens_1             | 23:29:34 0|api-toke |                  info: [Function: prepare_log_data],
api-tokens_1             | 23:29:34 0|api-toke |                  warn: [Function: prepare_log_data],
api-tokens_1             | 23:29:34 0|api-toke |                  error: [Function: prepare_log_data],
api-tokens_1             | 23:29:34 0|api-toke |                  fatal: [Function: prepare_log_data] },
api-tokens_1             | 23:29:34 0|api-toke |               prior: [Function],
api-tokens_1             | 23:29:34 0|api-toke |               good: [Function],
api-tokens_1             | 23:29:34 0|api-toke |               bad: [Function] } },
api-tokens_1             | 23:29:34 0|api-toke |         instance: 'Seneca/5nbd5oa1lyjg/1474500567307/16/3.1.0/-',
api-tokens_1             | 23:29:34 0|api-toke |         'orig$': 
api-tokens_1             | 23:29:34 0|api-toke |          { Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1"
api-tokens_1             | 23:29:34 0|api-toke |              at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:406:17)
api-tokens_1             | 23:29:34 0|api-toke |              at Connection.mainAccept [as accept] (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:63:33)
api-tokens_1             | 23:29:34 0|api-toke |              at Socket.go (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:476:48)
api-tokens_1             | 23:29:34 0|api-toke |              at emitNone (events.js:86:13)
api-tokens_1             | 23:29:34 0|api-toke |              at Socket.emit (events.js:185:7)
api-tokens_1             | 23:29:34 0|api-toke |              at emitReadable_ (_stream_readable.js:433:10)
api-tokens_1             | 23:29:34 0|api-toke |              at emitReadable (_stream_readable.js:427:7)
api-tokens_1             | 23:29:34 0|api-toke |              at readableAddChunk (_stream_readable.js:188:13)
api-tokens_1             | 23:29:34 0|api-toke |              at Socket.Readable.push (_stream_readable.js:135:10)
api-tokens_1             | 23:29:34 0|api-toke |              at TCP.onread (net.js:542:20) code: 406 },
api-tokens_1             | 23:29:34 0|api-toke |         'message$': 'Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1"',
api-tokens_1             | 23:29:34 0|api-toke |         plugin: {} },
api-tokens_1             | 23:29:34 0|api-toke |      callpoint: 'at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:406:17)' },
api-tokens_1             | 23:29:34 0|api-toke |   'message$': 'seneca: Action hook:listen,role:transport,type:amqp failed: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1".' }
api-tokens_1             | 23:29:34 0|api-toke | Stack: 
api-tokens_1             | 23:29:34 0|api-toke |     at Channel.C.accept (/home/service/api-tokens/node_modules/amqplib/lib/channel.js:406:17)
api-tokens_1             | 23:29:34 0|api-toke |     at Connection.mainAccept [as accept] (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:63:33)
api-tokens_1             | 23:29:34 0|api-toke |     at Socket.go (/home/service/api-tokens/node_modules/amqplib/lib/connection.js:476:48)
api-tokens_1             | 23:29:34 0|api-toke |     at emitNone (events.js:86:13)
api-tokens_1             | 23:29:34 0|api-toke |     at Socket.emit (events.js:185:7)
api-tokens_1             | 23:29:34 0|api-toke |     at emitReadable_ (_stream_readable.js:433:10)
api-tokens_1             | 23:29:34 0|api-toke |     at emitReadable (_stream_readable.js:427:7)
api-tokens_1             | 23:29:34 0|api-toke |     at readableAddChunk (_stream_readable.js:188:13)
api-tokens_1             | 23:29:34 0|api-toke |     at Socket.Readable.push (_stream_readable.js:135:10)
api-tokens_1             | 23:29:34 0|api-toke |     at TCP.onread (net.js:542:20)
api-tokens_1             | 23:29:34 0|api-toke | Instance: Seneca/5nbd5oa1lyjg/1474500567307/16/3.1.0/-
api-tokens_1             | 23:29:34 0|api-toke |     at Seneca.<anonymous> (/home/service/api-tokens/node_modules/seneca/lib/transport.js:46:23)
api-tokens_1             | 23:29:34 0|api-toke | When: 2016-09-21T23:29:34.467Z
api-tokens_1             | 23:29:34 0|api-toke | Log: {kind:null,plugin:seneca,tag:3.1.0,id:5nbd5oa1lyjg/1474500567307/16/3.1.0/-,code:transport_listen,notice:seneca
api-tokens_1             | 23:29:34 0|api-toke | Node:
api-tokens_1             | 23:29:34 0|api-toke |   { http_parser: '2.7.0', node: '6.4.0', v8: '5.0.71.60', uv: '1.9.1', zlib: '1.2.8', ares: '1.10.1-DEV', icu: '57.1', modules: '48', openssl: '1.0.2h' },
api-tokens_1             | 23:29:34 0|api-toke |   { debug: false, uv: true, ipv6: true, tls_npn: true, tls_alpn: true, tls_sni: true, tls_ocsp: true, tls: true },
api-tokens_1             | 23:29:34 0|api-toke |   [ 'Binding contextify', 'Binding natives', 'NativeModule events', 'NativeModule util', 'Binding uv', 'NativeModule buffer', 'Binding buffer', 'Binding util', 'NativeModule internal/util', 'NativeModule timers', 'Binding timer_wrap', 'NativeModule internal/linkedlist', 'NativeModule assert', 'NativeModule internal/process', 'Binding config', 'NativeModule internal/process/warning', 'NativeModule internal/process/next_tick', 'NativeModule internal/process/promises', 'NativeModule internal/process/stdio', 'Binding constants', 'NativeModule child_process', 'Binding spawn_sync', 'Binding pipe_wrap', 'NativeModule internal/child_process', 'NativeModule string_decoder', 'NativeModule net', 'NativeModule stream', 'NativeModule _stream_readable', 'NativeModule internal/streams/BufferList', 'NativeModule _stream_writable', 'NativeModule _stream_duplex', 'NativeModule _stream_transform', 'NativeModule _stream_passthrough', 'NativeModule internal/net', 'Binding cares_wrap', 'Binding tty_wrap', 'Binding tcp_wrap', 'Binding stream_wrap', 'NativeModule dgram', 'Binding udp_wrap', 'Binding process_wrap', 'NativeModule internal/socket_list', 'NativeModule cluster', 'NativeModule path', 'NativeModule module', 'NativeModule internal/module', 'NativeModule vm', 'NativeModule fs', 'Binding fs', 'Binding fs_event_wrap', 'NativeModule tty', 'NativeModule domain', 'NativeModule os', 'Binding os', 'Binding signal_wrap', 'NativeModule console', 'NativeModule http', 'NativeModule _http_incoming', 'NativeModule _http_common', 'Binding http_parser', 'NativeModule internal/freelist', 'NativeModule _http_outgoing', 'NativeModule _http_server', 'NativeModule _http_agent', 'NativeModule _http_client', 'NativeModule url', 'Binding icu', 'NativeModule querystring', 'NativeModule https', 'NativeModule tls', 'Binding crypto', 'NativeModule _tls_common', 'NativeModule _tls_wrap', 'NativeModule crypto', 'NativeModule internal/streams/lazy_transform', 'NativeModule _stream_wrap', 'Binding js_stream', 'Binding tls_wrap', 'NativeModule _tls_legacy', 'NativeModule dns' ]
api-tokens_1             | 23:29:34 0|api-toke | Process: 
api-tokens_1             | 23:29:34 0|api-toke |   pid=16, arch=x64, platform=linux,
api-tokens_1             | 23:29:34 0|api-toke |   path=/usr/local/bin/node,
  '--no-daemon' ],node_modules/pm2/lib/ProcessContainer.js',usr/local/bin/node',
  _pm2_version: '2.0.15' }51',]',2/pids/api-tokens-0.pid',or-0.log',n',rvice/api-tokens',
api-tokens_1             | 23:29:34 0|api-toke | SENECA TERMINATED at 2016-09-21T23:29:34.477Z. See above for error report.
api-tokens_1             | 2016-09-21 23:29:34: App name:api-tokens id:0 disconnected
api-tokens_1             | 2016-09-21 23:29:34: App [api-tokens] with id [0] and pid [16], exited with code [1] via signal [SIGINT]
api-tokens_1             | 23:29:34 PM2        | App name:api-tokens id:0 disconnected
api-tokens_1             | 23:29:34 PM2        | App [api-tokens] with id [0] and pid [16], exited with code [1] via signal [SIGINT]
```

I did some research and it seems to have something to do with acks option when setting up channels, but that's beyond my lvl, so was wondering if you have any immediate ideas?

Thanks again for your work on this!

**Comment by OriginalEXE** [comment]
Oh btw. I'm using the latest version of this plugin and Seneca 3.0.0

**Comment by nfantone** [comment]
That usually implies double ACK'ing or rejecting of a message. Did you upgrade RabbitMQ (or equivalent) recently? Did its configuration changed? Was `amqplib` updated?

I'll dig deeper into this and see what I can make of it. Could you provide a reproduceable scenario for the issue?

**Comment by OriginalEXE** [comment]
Hi,

your first sentence helped me find the issue, thanks a lot!

The problem was that I had a promise chain inside the seneca `add` `function( msg, done){}` callback, and I called `done` multiple times because I was not canceling the promise.

Sorry for bothering you with this :)

**Comment by nfantone** [comment]
@OriginalEXE No worries. Glad to help! I'll close the issue, but feel free to keep posting if you need to.
